version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    command:
      - "--default-authentication-plugin=mysql_native_password"
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
     - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  api:
    depends_on:
      - db
    build: ./temperature-api
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - DB_URL=jdbc:mysql://db:$MYSQLDB_DOCKER_PORT?useSsl=true
      - DB_USERNAME=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
    stdin_open: true
    tty: true
  front:
    depends_on:
      - api
    build: ./temperature-front
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - $FRONT_LOCAL_PORT:80
    stdin_open: true
    tty: true
volumes:
  db:
